добавлены хранилища, UserService и FilmService
m4nt4gWssup/java-filmorate pull request #3
Opened 2023-03-28 19:15 UTC by m4nt4gWssup

2023-03-29 17:45 UTC, TarasovSam requested changes
Пётр, привет!
Проверил твое задание, спасибо за работу. Оставил комментарии с тем, что можно улучшить и что нужно поправить, плюс пару вопросов)
И поправь то, что я написал тебе в пачку, чтобы сборка проекта проходила на гите.
Жду твою работу на следующую итерацию!) Если будут вопросы, пиши в пачку)

2023-03-29 17:45 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
В принципе все хорошо, но дополнительно можно провести логирование в каждом методе. К тому же при логировании можно использовать коды (которые были в ТЗ). Они общеизвестны и понятны всем, ну многим точно)

2023-03-29 17:45 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.getAllFilms();
Почему здесь вызываешь метод Storage, а не Service?
Принята следующая система: в контроллере идет вызов методов сервиса, а уже в методах сервиса можно вызывать методы других компонентов.
В других методах и для контроллера пользователя тоже самое.

2023-03-29 17:45 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getPopular(count);
А почему здесь и в некоторых других методах не проводишь логирование?

2023-03-29 17:45 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        userService.addFriend(id, friendId);
А почему здесь и в методе deleteFriend не проводишь логирование?

2023-03-29 17:45 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Integer rate() {
Хорошая идея выделить в отдельное поле рейтинг фильма.

2023-03-29 17:45 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                throw new UserNotFoundIdException("Пользователь c ID=" + userId + " не найден!");
"Неудачные" попытки запросов тоже можно логировать для полноты картины)

2023-03-29 17:45 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService {
В сервис нужно будет добавить все CRUD методы, которые вызываются в контроллере.
Для пользователя тоже самое.

2023-03-29 17:45 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +public interface FilmStorage {
Методы для FilmStorage и UserStorage идентичны, поэтому можно их выделить в интерфейс с использованием дженериков.
Тоже самое можно сделать и для InMemoryStorage, но там несколько замороченнее)
Это рекомендация к рассмотрению.

2023-03-29 17:45 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new FilmNotFoundIdException("Такого id - " + film.getId() + " не существует");
Тут по сути тоже можно проводить логирование "неудачных" попыток.
Для пользователя тоже.

2023-03-29 17:45 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +public interface UserStorage {
А в FilmStorage методы через пустую строку написал)

2023-03-29 18:13 UTC, m4nt4gWssup commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.getAllFilms();
Потому что в ТЗ сказано, что методы из старого контроллера мы должны закинуть в Storage, а в Service только новые функции, поэтому так и сделал

2023-04-04 17:12 UTC, m4nt4gWssup commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new FilmNotFoundIdException("Такого id - " + film.getId() + " не существует");
Здесь и так происходит логирование, так как в классе исключения у нас уже прописан log

2023-04-04 18:24 UTC, TarasovSam approved these changes
Пётр, проверил твое задание, спасибо за работу и за то, что дорабатываешь код (в том числе и сверх нормы так сказать).
Задание я принимаю, успеха в обучении и до следующего спринта!) Если будут вопросы, пиши в пачку.

2023-04-20 13:40 UTC, merged